/**
 * A deadline for work that has an HTTP response waiting on it.
 *
 * Why this exists: the orchestrator sits behind Cloudflare, which cuts an origin request at 100
 * seconds and answers with its OWN error page. That page is generated by the proxy, so it does not
 * carry the origin's `Access-Control-Allow-Origin` header, and a browser rejects a cross-origin
 * response with no CORS header as a network failure. The result is `TypeError: Failed to fetch`,
 * which is indistinguishable from the service being down: the picker reported "Could not reach the
 * chat service" about a service that was up and had answered a health check seconds earlier.
 *
 * So the origin has to be the one that gives up. Answering 504 from here keeps the response inside
 * our own CORS middleware, which means the client receives a status and a message it can show
 * instead of a browser-level failure it has to guess about.
 *
 * The work itself is NOT cancelled. An MCP tool call in flight has no abort channel, so this bounds
 * how long a caller waits, not how long the child process works. The pool entry is released by the
 * caller's `finally` either way.
 */
export class DeadlineError extends Error {
  readonly code = 'timed_out';

  constructor(message: string, readonly waitedMs: number) {
    super(message);
    this.name = 'DeadlineError';
  }
}

/**
 * Resolves with `work`, or rejects with a DeadlineError once `ms` have passed.
 *
 * A non-finite or non-positive `ms` disables the deadline rather than firing immediately, so a
 * misconfigured environment variable cannot turn every request into a timeout.
 */
export function deadline<T>(work: Promise<T>, ms: number, message: string): Promise<T> {
  if (!Number.isFinite(ms) || ms <= 0) return work;

  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new DeadlineError(message, ms));
    }, ms);
    // Never hold the process open for a deadline that no longer matters.
    timer.unref?.();

    work.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (err: unknown) => {
        // Clear first: a rejection that lost the race must still not leave the timer armed, or a
        // request that already failed fast would log a phantom timeout later.
        clearTimeout(timer);
        reject(err);
      },
    );
  });
}
