/**
 * The Community Template Gallery index: every template and the GitHub owner that publishes it.
 *
 * WHY THIS EXISTS: importing a gallery template needs an owner AND a repository, and a wrong
 * guess returns a bare 404 that reads as "this template does not exist" rather than "you spelled
 * it wrong". The owner is the half that cannot be inferred from the product name (Microsoft
 * Clarity is published by both microsoft and luratic; Hotjar-branded templates come from
 * gtm-templates-knowit-experience), so having it turns an unbounded guess into a narrow one.
 *
 * WHAT THIS IS NOT: it does not carry the repository. Read that off the template page in the
 * gallery, or attempt the import and let its idempotent check answer. Never present an
 * owner/repository pair as confirmed unless an import actually succeeded.
 *
 * Generated from the gallery listing captured 2026-08-27. The gallery changes constantly, so a
 * miss means "not in this snapshot", never "not available".
 */

/** [template name, GitHub owner] */
export const GALLERY_TEMPLATES: readonly (readonly [string, string])[] = [
  ["000 ClickPatrol Ad Traffic Quality", "ClickPatrol"],
  ["100shoppers Where To Buy Widget Script", "buybox"],
  ["2BCookie Consent Manager", "2B-Advice"],
  ["500apps - Botup", "agilecrm"],
  ["500apps - Forms.io", "agilecrm"],
  ["500apps - SiteRecording", "agilecrm"],
  ["6sense Account Engagement Pixel", "Quadratic-Insights"],
  ["AAA WCAG 2.2 with adaptor.app", "adaptor-app"],
  ["AAANOW ACM Accessibility Panel Loader", "unceasing-dev"],
  ["Abralytics", "tomasmck"],
  ["ABTShield", "EDGE-NPD"],
  ["Acceptrics CMP", "Acceptrics"],
  ["Accessibility by Accessibly", "on-the-map"],
  ["Accessibility by AI-Powered Binclusive", "Binclusive"],
  ["Accessibility by All in One Accessibility", "skynettechnologies"],
  ["Accessibility by AudioEye", "audioeye"],
  ["Accessibility by CorpoWid", "corpowid"],
  ["Accessibility by Inclusif", "inclusif-life"],
  ["Accessibility by UserWay", "UserWayOrg"],
  ["Accessibility by WelcomingWeb", "welcomingweb"],
  ["AccessiWeb Widget", "dunpcloud"],
  ["AccessiWeb Widget", "elonghidunpit"],
  ["Acconsento.click Consent Manager by netWork", "Network-SAS"],
  ["Acquia Optimize script", "F-Lourenco80"],
  ["Acquia Personalization Capture", "acquia"],
  ["Acquire", "acquireio"],
  ["Across Simple Conversion Code", "across-it"],
  ["ActionSpeak Show Popup Tag", "action-speak"],
  ["ActiveCampaign Site Tracking by New North", "newnorthdigital"],
  ["Ad Click ID Storer", "dpezrez"],
  ["ADCELL - 1st-Party-Tracking", "ADCELL"],
  ["ADCELL - Conversiontracking", "ADCELL"],
  ["AdDaptive Intelligence Site Analytics", "AdDaptive"],
  ["Addressable Pixel", "addressableid"],
  ["Addrevenue - Tracking tag", "addrevenue-io"],
  ["Adform Tracking", "peaksandpies"],
  ["Adform Tracking Point", "gtm-templates-simo-ahava"],
  ["AdGlare Ad Tag", "adglare"],
  ["Adgravity", "luratic"],
  ["Adhoc Pixel", "Used-case-dev"],
  ["AdMaxim Retargeting Pixel", "harshmohta"],
  ["AdMaxim Smart Pixel", "harshmohta"],
  ["Admitad Journey", "AdmitadSDK"],
  ["Admitad Tracking", "AdmitadSDK"],
  ["Admixer Conversion Tag", "AdmixerTech"],
  ["AdOpt", "goadopt"],
  ["Adot Campaign Pixel", "adotmob"],
  ["AdPage Data Assistant", "AdPageGroup"],
  ["AdScout Integration", "adscout-io"],
  ["AdService", "gtm-templates-simo-ahava"],
  ["AdSimple - Consent Manager for WordPress", "AdSimple-GmbH"],
  ["Adsmurai Facebook, TikTok, Pinterest, Snapchat Pixel & Conversions API (CAPI)", "Adsmurai-Google-Tag-Manager-Templates"],
  ["Adsmurai Visual Commerce", "luratic"],
  ["AdTiming Tag", "Adtiming"],
  ["Advanced Consent Mode v2 Banner", "analyticskgmedia"],
  ["Advanced Custom Event Push", "alessandrosalerno"],
  ["Advertience Attribution Linker", "advertience-inc"],
  ["Adwize - Data collection monitoring", "Adwize"],
  ["Adxcg Simple Pixel", "adxcgcom"],
  ["Adyoulike", "luratic"],
  ["Affilae - Click Tag", "AffilaeTech"],
  ["Affilae - Conversion Tag", "AffilaeTech"],
  ["Affirm", "Affirm"],
  ["AffOcean", "luratic"],
  ["Afilio Mastertag V3", "afiliohub"],
  ["Afilio Pixel", "afilio-ti"],
  ["Afilio Tag", "afilio-ti"],
  ["Agada Pixel", "Agada-Tech"],
  ["Ahrefs Web Analytics Unofficial", "Jude-Nwachukwu"],
  ["AIDEM Stream", "AIDEM-Technologies"],
  ["Aimwel Conversion Measurement Tag", "Aimwel-OS"],
  ["AjaxRequestListener", "frodestorhaug"],
  ["Albacross Tracking", "albacross"],
  ["Alevco", "alevco"],
  ["Algolia Search Insights", "algolia"],
  ["Algolia Search Insights", "analytics-debugger"],
  ["Along Information Commenting Platform", "get-along-io"],
  ["Alphalyr Marketing Studio", "Alphalyr"],
  ["AltTextLab Alt Text Generator", "alttextlab"],
  ["Amadeus MetaConnect Conversion Tracking", "AmadeusITGroup"],
  ["Amadeus MetaConnect Flight Preselection", "AmadeusITGroup"],
  ["Amazon", "luratic"],
  ["Amazon Advertising Tag", "amzn"],
  ["Amio chat widget", "LukasAmio"],
  ["amoCRM CRM Plugin", "amocrm"],
  ["Amplitude Analytics Browser SDK", "amplitude"],
  ["Amplitude Analytics Legacy", "amplitude"],
  ["AnnounceKit", "announcekitapp"],
  ["Anonymised Marketing Tag", "id-ward"],
  ["Anura Solutions, LLC", "anuraio"],
  ["AnyTrack Tracking Tag", "anytrack"],
  ["Apex Chat", "justia"],
  ["Appcues", "gtm-templates-simo-ahava"],
  ["AppNexus", "gtm-templates-simo-ahava"],
  ["Appservation User Analytics", "BytesMatter"],
  ["Argoid Data Collector - Shopify", "Argoid"],
  ["Aroa Sync", "DatMeanSpain"],
  ["Arukereso", "pavelsabatka"],
  ["Ascend by Partnerize", "pepperjam"],
  ["AT Internet - SmartTag by 55", "at-internet"],
  ["Atrilyx", "AiMediaGroup"],
  ["Attentive Analytics SDK", "attentive-mobile"],
  ["Attribution Insight Tag", "Jude-Nwachukwu"],
  ["Atwave", "atwave-web"],
  ["AudienceProject Data to dataLayer", "audienceproject"],
  ["AudienceProject UserReport", "gtm-templates-simo-ahava"],
  ["AudienceTown Tag", "Audience-Town"],
  ["Avacy CMP", "jump-group"],
  ["Avo Inspector", "avohq"],
  ["Awin - AW Last Click Identifier", "awin"],
  ["Awin Advertiser Mastertag", "EdinCuturic"],
  ["Awin Consent Signals", "awin"],
  ["Awin Conversion Tag", "EdinCuturic"],
  ["Axeptio CMP", "axeptio"],
  ["backTrack - dataLayer Event Re-Pusher", "mohrstade"],
  ["Baldwin TikTok Transaction", "baldwin-agency"],
  ["Bambuser Live Shopping", "bambuser"],
  ["Barilliance", "analytics-debugger"],
  ["beehiiv Event Tag", "beehiiv"],
  ["beehiiv Pixel V2", "beehiiv"],
  ["Belboon Container Tags", "luratic"],
  ["Belboon Performance Marketing Tracking Code", "luratic"],
  ["Beslist event", "analyticsatbeslistpuntnl"],
  ["BeTag", "giep-br"],
  ["Beyond Beacon", "1024inc"],
  ["Biano Pixel", "BianoCZ"],
  ["Biano Pixel for Shoptet", "BianoCZ"],
  ["Biano Similarity", "BianoCZ"],
  ["BigID Cookie CMP", "bigexchange"],
  ["Billy Grace - Configuration Web Pixel", "Billy-Grace"],
  ["Billy Grace - Web Event", "Billy-Grace"],
  ["Bizrate Insights Online Buyer Solution", "bizrateinsights"],
  ["Black Crow AI", "october8ai"],
  ["Blind Creator Tag", "Blind-Creator-Inc"],
  ["Blitzllama Tag", "Blitzllama"],
  ["Bloomreach Discovery Pageview Tag (unofficial)", "martijnvv"],
  ["Blue Green Analytics", "bluegreenbrands"],
  ["Blueconic", "MISTAnalytics"],
  ["Bluekai Oracle Dmp", "luratic"],
  ["Blutic Cookie Manager", "Blutic-club"],
  ["BMS Universal Tag", "Blue-Media-Services"],
  ["Booster Box - UTMs Storing", "Precis-Digital"],
  ["Botfaqtor code", "Botfaqtor"],
  ["Bounce Commerce Integration", "bounce-commerce"],
  ["BrainSINS", "analytics-debugger"],
  ["Braze Actions Tag", "braze-inc"],
  ["Braze Initialization Tag", "braze-inc"],
  ["Brevo Tracker", "newnorthdigital"],
  ["Broadciel Pixel", "Broadciel"],
  ["Browsee", "Browsee"],
  ["Bulk Cookie Setter (Smart)", "Jude-Nwachukwu"],
  ["BUY.BOX Core Script Tag", "buybox"],
  ["BUY.BOX Order Script Tag", "buybox"],
  ["BUY.BOX Where To Buy Widget Script", "buybox"],
  ["Cadent Pixel", "zdrom"],
  ["CAKE", "cake-labs"],
  ["CallPage widget", "callpage"],
  ["CallRail - Dynamic Number Insertion", "jaredrileysmith"],
  ["Campaign Collector", "LevelInteractive"],
  ["Captain Compliance CMP", "Captain-Compliance"],
  ["Captiv8 Affiliate Tracking - Conversion Tag", "captiv8io"],
  ["Captiv8 Affiliate Tracking - Journey Tag", "captiv8io"],
  ["Captivated Messaging", "CaptivatedLLC"],
  ["Capture Partnerize Click Reference", "PZ-it-admin"],
  ["Carbon", "carbondmp"],
  ["Carrot quest", "carrotquest"],
  ["CDNJS - Hosted Libraries", "gtm-templates-simo-ahava"],
  ["Channel.io", "channel-io"],
  ["ChannelAdvisor Sales Tracking", "channeladvisor"],
  ["Chartbeat Web Tracking Tag", "iCompetence"],
  ["Chatbase Widget", "gutewebsites"],
  ["Chatbot.com widget", "nottinghamcollege"],
  ["Checkout Timer", "mbaersch"],
  ["Checkpoint Pixel", "Know-That-Ai"],
  ["CHEQ Enforce", "cheq-ai"],
  ["CHEQ Essentials", "cheq-ai"],
  ["CHEQ Manage - Server-Side Tagging - Event", "cheq-ai"],
  ["CHEQ Manage - Server-Side Tagging - Web SDK", "cheq-ai"],
  ["CJ Affiliate - Legacy Conversion Tag", "cj-support"],
  ["CJ Affiliate - Universal Tag", "cj-support"],
  ["ClearBrain Pixel", "clearbrain"],
  ["CleverPush", "cleverpush"],
  ["Click IDs Manager", "jonah-onyejekwe"],
  ["ClickDefense Pixel", "click-defense"],
  ["Clickio Consent", "ClickioTech"],
  ["ClickPatrol - Conversion", "ClickPatrol"],
  ["ClickReport", "webminds-inc"],
  ["Clicktripz Universal Tag", "ClickTripz"],
  ["Clickwise Pixel", "Guubal"],
  ["Cloudflare Web Analytics", "yuhui"],
  ["Cludo Search", "Cludo"],
  ["Clym CMP", "clymio"],
  ["Code Cube Tag Monitor Template", "irasanCC"],
  ["Codenbutter", "codenbutter"],
  ["Collecting user input data", "redsquad-tech"],
  ["Commanders Act CMP", "CommandersAct"],
  ["Commands Tag", "giovaniortolani"],
  ["Complianz.io - The Privacy Suite for WordPress", "complianz"],
  ["Concise Media Conversion Tag", "ConciseMedia"],
  ["Concord CMP", "concord-tech"],
  ["Conductrics", "gtm-templates-simo-ahava"],
  ["ConferWith Google Tracking", "conferwith"],
  ["Conferwith Tracking", "mobappmart"],
  ["Connects", "connects-tech"],
  ["Connextra", "gtm-templates-AndySN"],
  ["Consent Granted Listener", "analytics-engineers"],
  ["Consent Listener for Tag Rocket on BigCommerce", "Tiggerito"],
  ["Consent Mode (Free) - Toolz", "Toolz-at"],
  ["Consent Mode (Google + Microsoft tags)", "gtm-templates-simo-ahava"],
  ["Consent Mode API 中文化範本", "spyder-com-tw"],
  ["Consent Mode GTM - Skillonnet", "mtechraw"],
  ["Consent Pro - GTM Template", "finsweet"],
  ["Consent Studio CMP", "vallonic"],
  ["ConsentBanner v.202", "max-bre"],
  ["ConsentCheck – Consent Mode v2 Default", "marstay"],
  ["Consentik GDPR CMP", "consentik"],
  ["Consently CMP", "dorik"],
  ["consentmanager.net CMP & Cookie Banner", "consentmanager"],
  ["Consentmo GDPR CMP", "consentmo"],
  ["Container Injector", "jamescottrill"],
  ["Contentsquare - Artificial Pageview", "contentsquare-ps"],
  ["Contentsquare - Custom Errors", "contentsquare-ps"],
  ["Contentsquare - Dynamic Variables", "contentsquare-ps"],
  ["Contentsquare - E-commerce data", "contentsquare-ps"],
  ["Contentsquare - E-commerce data (unofficial)", "martijnvv"],
  ["Contentsquare - ETR Event", "contentsquare-ps"],
  ["Contentsquare - Main tag", "contentsquare-ps"],
  ["Contentsquare - Page Events", "contentsquare-ps"],
  ["Contentsquare - Tracking Customization", "contentsquare-ps"],
  ["Contentstack Personalize Actions", "contentstack"],
  ["Contimo", "contimo-io"],
  ["Conversions Manager", "mbaersch"],
  ["Convertix Eventos PT-BR", "convertix-digital"],
  ["Convery", "luca-convery"],
  ["Convious Script", "Convious"],
  ["Conviva DPI JS SDK", "Conviva"],
  ["Conzent CMP", "conzent-net"],
  ["Cookie Confirm CMP", "Cookie-Confirm"],
  ["Cookie Creator", "gtm-templates-anto-hed"],
  ["Cookie Information + Consent Mode v2", "cookie-information"],
  ["Cookie Information Consent Mode", "cookie-information"],
  ["Cookie Saver Configuration", "Cookie-Saver"],
  ["Cookie Setter (Smart)", "Jude-Nwachukwu"],
  ["Cookiebanners.nl Tag Template", "digidays"],
  ["CookieBeam Consent Mode", "cookiebeam"],
  ["Cookiebot CMP", "Usercentrics"],
  ["Cookiebox", "cookiebox-conversion"],
  ["CookieConsent.io", "cookieconsentio"],
  ["CookieConsent.io - Enhanced Conversions", "cookieconsentio"],
  ["CookieConsent.io - Facebook Server 2 Server template", "cookieconsentio"],
  ["CookieConsent.io - Pinterest Server 2 Server template", "cookieconsentio"],
  ["CookieConsent.io - TikTok Server 2 Server template", "cookieconsentio"],
  ["CookieDialog (CMP)", "MarketVision-Ltd"],
  ["CookieFirst CMP integration (Consent Mode v2)", "cookiefirst"],
  ["CookieFrame CMP", "cookieframeapp"],
  ["Cookiefy - Consent Mode", "SUNROS-AB"],
  ["CookieHub CMP", "cookiehub-com"],
  ["CookieHug Consent Banner", "cookiehug-com"],
  ["CookieLegit Cookie Consent", "CookieLegit"],
  ["CookieMan CMP for Privacy Compliant", "MLInformatica"],
  ["Cookienovo", "Cookienovo"],
  ["CookiePal CMP", "cookiepal"],
  ["CookiePlus CMP", "cookieplus-cmp"],
  ["Cookies and Click IDs extractor and consolidator", "shulhat"],
  ["Cookies Správně", "CookiesSpravne"],
  ["CookieScan", "cookiescan"],
  ["CookieScript CMP (Consent Mode)", "Cookie-Script"],
  ["CookieTractor CMP (Consent Mode v2)", "CookieTractor"],
  ["CookieYes CMP", "cookieyeshq"],
  ["CookieZen CMP", "Semavoo"],
  ["Cookifi - Reliable Consent Management", "cookifi-cmp"],
  ["Core Web Vitals", "gtm-templates-simo-ahava"],
  ["Countly Analytics", "Countly"],
  ["Coveo Analytics", "coveo"],
  ["CRED Pixel", "CRED-CLUB"],
  ["Crisp Chat", "crisp-im"],
  ["Criteo", "House-of-Rezac"],
  ["Criteo Loader - Official", "criteo"],
  ["Criteo OneTag - Official", "criteo"],
  ["Criteo S2S v2 - Client", "criteo"],
  ["Criteo User Identification", "criteo"],
  ["CrossEngage Tracking SDK Config", "CrossEngage"],
  ["CrossEngage Tracking SDK Event", "CrossEngage"],
  ["CrowdHandler Javascript Template", "Crowdhandler"],
  ["CryptoMe", "120feet"],
  ["Custom Adless Integration", "adless-tech"],
  ["Custom Cookie Tag", "GrowthSavvy"],
  ["Custom DataLayer Event with Variables", "anooptu"],
  ["custom params", "Knapstad"],
  ["Custom Session Manager", "mbaersch"],
  ["CustomerGauge Pop-Up Survey", "cgauge"],
  ["Cybba", "cybba"],
  ["Cybexo CMP", "Cybexo"],
  ["CYTRIO Cookie Consent Template", "Cytrio"],
  ["D-EDGE - Mediagenius linker - For 3rd Party BEs", "D-Edge-WebStudio"],
  ["D-EDGE - Mediagenius linker - For D-EDGE BEs", "D-Edge-WebStudio"],
  ["D36i Attribution Linker", "d36i-analytics"],
  ["Dable Conversion Script", "teamdable"],
  ["Daisycon Conversion Tag", "DaisyconBV"],
  ["Daisycon Synergy Tag (Server Side/Hybrid fallback)", "DaisyconBV"],
  ["dash.fi Ad Pay Protection", "FunnelDash"],
  ["Dashly", "carrotquest"],
  ["Data Hash For PII", "EbrahimHendawy"],
  ["Data Tag", "stape-io"],
  ["Datadog RUM Browser SDK", "martijnvv"],
  ["DataLayer Backup", "yugin-pro"],
  ["dataLayer Builder + Enhanced Ecommerce", "Mikeulrich75"],
  ["dataLayer Builder + GA4 Ecommerce", "wpromote"],
  ["dataLayer Builder + Standard Ecommerce", "Mikeulrich75"],
  ["DataLayer Event Repeater", "mbaersch"],
  ["DataLayer Push Custom Event", "TD-turingdigital"],
  ["DataReporter WebCare CMP V2.0", "datareporter-gmbh"],
  ["Dataroid", "dataroid"],
  ["Datm Web Analytics Tag", "curtis2point1"],
  ["Demandbase One Tag (Unofficial)", "Jude-Nwachukwu"],
  ["Deprecated Sovendus Integration for Sales and Select", "Sovendus-GmbH"],
  ["DerbySoft Marketing Services - Event Tag", "DerbySoft"],
  ["Deway Web SDK", "Deway-AI"],
  ["Dialogue", "dialogueai"],
  ["Did someone clone me?", "didsomeonecloneme"],
  ["Didomi CMP", "didomi"],
  ["Diduenjoy Survey Pop Up", "Diduenjoy"],
  ["Digiseg Insights Platform", "digiseg-labs"],
  ["Digitalsterne Cookie Master", "Digitalsterne-GmbH"],
  ["Digitalsterne Site Tag", "Digitalsterne-GmbH"],
  ["Digitalsterne Site Tag Free", "Digitalsterne-GmbH"],
  ["Dinamize - Script Automation", "Dinamize"],
  ["Discovery Pixel dev", "popIn-Discovery"],
  ["DMP Tags - Template", "dev-wihp-cendyn"],
  ["dooshop Tracking", "dooshop"],
  ["Drezzy Pixel", "DrezzyIt"],
  ["Drift Pixel", "attriva"],
  ["E-Commerce Taboola pixel", "taboola"],
  ["E-goi", "luratic"],
  ["E-Space Surveys", "extellio"],
  ["eagle-insight-tag", "mercari"],
  ["EASI DSP Pixel", "GiftConnect"],
  ["easyfeedback Tracking Code", "easyfeedback"],
  ["EBOD Purchase Tracking Script", "ebod-digital"],
  ["Ecommerce Impressions/Items Chunk Size", "gtm-templates-knowit-experience"],
  ["Ediscom Simple Conversion Code", "ediscom"],
  ["Edmonlytica Browser Tag", "MarkEdmondson1234"],
  ["EdTech Impact", "gtm-templates-simo-ahava"],
  ["Efilli CMP", "efilli"],
  ["Elevar Monitoring Core Tag", "getelevar"],
  ["Elevar Monitoring Tag Info", "getelevar"],
  ["Elle", "joseariel"],
  ["Elmo", "elmo-vc"],
  ["Ematic Pixel", "Ematicexternal"],
  ["Empathy.co search - interactions", "empathyco"],
  ["Empathy.co search - query", "empathyco"],
  ["Encrypt (Hash) Sensitive Data", "leoschuler"],
  ["Engage-X Pixel", "engageXio"],
  ["EnkeltPersonvern.no", "Funbit-AS"],
  ["Enzuzo Cookie Manager", "enzuzo"],
  ["EPA Purchase", "epa-datos"],
  ["Epsilon Site Tag", "EpsilonDataManagement"],
  ["Equalweb", "luratic"],
  ["Eulerian Analytics - Advanced Plugin", "EulerianTechnologies"],
  ["Eulerian Marketing Platform", "EulerianTechnologies"],
  ["Event Parameter Hasher", "gtm-templates-pmeyerdk"],
  ["Event/Pageview Cookie Counter", "Jude-Nwachukwu"],
  ["Evidon - Universal Consent Platform", "EvidonCMP"],
  ["Exatom Audience Tag", "exatom-io"],
  ["Exatom Conversion Tag", "exatom-io"],
  ["Exatom Event Tag", "exatom-io"],
  ["Exponea Tag", "exponea"],
  ["External Script Loader", "mbaersch"],
  ["EyeOne Widget", "marcin-bizuga"],
  ["Facebook CAPI Tag", "peaksandpies"],
  ["Facebook Conversion Linker", "signaly-io"],
  ["Facebook Conversions API (CAPI) by Deviate Tracking", "DeviateLabs"],
  ["Facebook Customer Chat", "facebookarchive"],
  ["Facebook Pixel by Effectix", "Effectix-com"],
  ["Facebook Pixel by Stape", "stape-io"],
  ["Facebook Pixel by TrackingHippo.io", "trackinghippo-io"],
  ["Faslet's Size Me Up", "Faslet"],
  ["FAST Conversion", "smarketer-de"],
  ["FAST Script", "smarketer-de"],
  ["Fatmedia Tag", "fatmedia-io"],
  ["FAVI Partner Events Tracking", "favionline"],
  ["FigPii", "figpii"],
  ["Finder Partner Tag", "finderau"],
  ["Firebase Analytics Handler Global Variable Initialization", "giovaniortolani"],
  ["Firestore Web Tag", "ArtemKorneevGA"],
  ["Firework Videos", "loopsocial"],
  ["FirstImpression.io Integration Tag", "firstimpression-io"],
  ["FitAnalytics - Fit Finder", "luratic"],
  ["FitConsent", "DIGITLOAD-CA"],
  ["Fitmedia Retargeting and Conversion Pixel", "leohck"],
  ["Fixel", "fixel-ai"],
  ["FlareLane", "flarelane"],
  ["Floup AI Customer support chatbot", "Ryan1211"],
  ["Flowappz Cookie Consent GTM Template", "Flowappz"],
  ["Flytant Ads Pixel", "flytant"],
  ["Flytxt Insights", "flytxt"],
  ["FouAnalytics", "henkisdabro"],
  ["Fraudlogix for Programmatic", "fraudlogix"],
  ["Frenzy Events", "frenzyopensrc"],
  ["Freshpaint", "freshpaint-io"],
  ["Fullstory - Browser Tag", "fullstorydev"],
  ["Fullstory Advanced Unofficial", "Jude-Nwachukwu"],
  ["Funnelytics", "Funnelytics"],
  ["Furniture.com pixel", "Furniture-com"],
  ["G2DM - Conversion", "capterra-public"],
  ["G2DM - Universal Script", "capterra-public"],
  ["GA4 Ecommerce", "cakmakumut"],
  ["GA4 Ecommerce Validator", "george-clements"],
  ["GA4 Event with built-in Hit Timestamp and Client ID", "turingdigital-analytics"],
  ["GA4 Events Importer", "Andiministrator"],
  ["GA4 for javascript interface.", "pluszero-global"],
  ["GA4 Recommended Event Builder", "pluszero-global"],
  ["GA4 User-Properties", "TD-turingdigital"],
  ["Gauss Tag - Event", "makingscience-gausstag"],
  ["Gauss Tag Configuration", "makingscience-gausstag"],
  ["Generic GET Request", "merkle-es"],
  ["Geolid Tracker", "Geolid"],
  ["Getback Tag", "adfocus-tech"],
  ["getContext - Official", "SamuelBreton"],
  ["Getquanty Live Zapier", "Getquanty"],
  ["GetQuanty Tracker", "Getquanty"],
  ["Getsitecontrol", "getsitecontrol"],
  ["GetTerms CMP", "GetTerms"],
  ["Gifty Order Module", "giftyhq"],
  ["Gimii - Consent raiser", "Gimii-solutions"],
  ["GLAMI piXel", "glami"],
  ["GLAMI piXel v2", "glami"],
  ["GLAMI TOP", "glami"],
  ["GLP Winner Tracking", "GLP-Winner"],
  ["Glückauf Tag", "allvintage"],
  ["Goaffpro Affiliate Marketing", "anujtenani"],
  ["GoldLantern Tracking Pixel", "InfiniteProfitSolutions"],
  ["Google Chat Webhook (Bot)", "henkisdabro"],
  ["Google Consent for Dotter Application", "dotterme"],
  ["Google Consent Mode", "SirDataFR"],
  ["Google Customer Reviews Tag by Stape", "stape-io"],
  ["Google Ecommerce data transfer", "d9i2r2t1"],
  ["Google Sheets - Lato Client", "DC7711"],
  ["Google Sheets Webhook", "agolca123"],
  ["Google Tag Manager Monitor", "gtm-templates-simo-ahava"],
  ["Gorgias Chat", "gorgias"],
  ["GPixel", "globoi"],
  ["Gravito CMP", "GravitoLtd"],
  ["Grow", "upstreamsystems"],
  ["Grow - Track Ecommerce Event", "upstreamsystems"],
  ["GrowthBook Feature Flags and Experimentation", "growthbook"],
  ["GTAG GET API", "gtm-templates-simo-ahava"],
  ["GTM Consent Configuration (Consent Mode)", "taneli-salonen1"],
  ["GTM Consent Listener", "Ayudante"],
  ["GTM Monitoring in Google Analytics", "zjuul"],
  ["Gumstack", "gumstack"],
  ["Hackle Browser SDK", "hackle-io"],
  ["Hash Tag (sha256)", "nerolation"],
  ["Hatch Conversion Tag", "HatchBV"],
  ["heatmap.com", "cideck"],
  ["Helio Attribution Linker", "MadeByHelio"],
  ["Hero Ecommerce Tracking", "usehero"],
  ["Hero Messenger", "usehero"],
  ["Heureka", "pavelsabatka"],
  ["Heylink", "MikkelSnitker"],
  ["Heylink", "teamheylink"],
  ["HG Conversion measurement", "heureka"],
  ["Homefiniti Analytics", "oneilinteractive"],
  ["Honest-Metrics", "Honest-Metrics"],
  ["Hotjar Event", "gtm-templates-knowit-experience"],
  ["Hotjar User Attributes", "gtm-templates-knowit-experience"],
  ["HQ revenue Pixel", "hq-developer"],
  ["HTML Media Elements Tracker", "analytics-debugger"],
  ["HubSpot", "luratic"],
  ["Hubspot CMP - Hubspot cookie banner integration", "avoy18"],
  ["HubSpot Script Tag", "trackify-info"],
  ["Humanitix Echo", "humanidevs"],
  ["Humanz pixel", "humanzai"],
  ["Hunch", "tweex-technologies"],
  ["HypeSaaS widget", "SilverGhostBS"],
  ["Hyvor Talk (Unofficial)", "nebulae-software"],
  ["iAdvize - Custom Data tag", "iadvize"],
  ["iAdvize - Main tag", "iadvize"],
  ["iAdvize - Transaction tag", "iadvize"],
  ["ICOMM WebPush Invoke Script", "ICOMMKT"],
  ["iConvert Core Tracking", "iconvert-mk"],
  ["Idealmedia Pixel", "idealmedia"],
  ["Ideta", "IdetaAutomation"],
  ["IDX", "ffqs"],
  ["IGB Tracker", "InGoedeBanen"],
  ["illow Cookie CMP", "illow-io"],
  ["Immerss Live", "Immerss"],
  ["Immerss Tracking Order", "Immerss"],
  ["Immerss Tracking Visit", "Immerss"],
  ["Immerss Widget", "Immerss"],
  ["Impresee", "Impresee"],
  ["Improved Google Marketing Tags using gtag", "giovaniortolani"],
  ["Improved LinkedIn Insight Tag", "WebMechanix"],
  ["INB Marketing CMP", "kampanie-inb"],
  ["indemandly", "indemandly"],
  ["Indicative Analytics", "Indicative"],
  ["Infoset", "Infoset"],
  ["inQuba Journey Tracker", "prinayinq"],
  ["Insider", "hypeagency"],
  ["Instant Recall Widget", "missena-corp"],
  ["InstantAlt Automatic Alt Text", "alttextai"],
  ["Instinctive Universal Analytics", "InstinctivePlatform"],
  ["Instyle Analytics", "sudolabs-io"],
  ["Intent", "intentmedia"],
  ["intent.ly", "smarterclick"],
  ["Intercom", "intercom"],
  ["Intercom API Connector (Unofficial)", "Bind-Media"],
  ["IP Geolocation", "devjfreaks"],
  ["IP Geolocation API", "gtm-templates-simo-ahava"],
  ["IP LYTICS", "iplytics-admin"],
  ["IpMeta GA4 plugin", "nottinghamcollege"],
  ["IpMeta.io for GA4", "henkisdabro"],
  ["IQM", "iqmcorp"],
  ["iubenda Privacy Controls and Cookie Solution", "iubenda"],
  ["jam.dev", "rohailaltaf"],
  ["Jobcase, Inc. Partner Action Tracking Tag", "jobcaseinc"],
  ["Join Stories - Add to Cart Tracking Code", "teamjoin"],
  ["Join Stories - Checkout Tracking Code", "teamjoin"],
  ["Join Stories - Conversions Custom Code", "teamjoin"],
  ["Join Stories - Global Script", "teamjoin"],
  ["Jooble conversion", "jooble-gtm-official"],
  ["Jooble conversion initialize", "jooble-gtm-official"],
  ["Joonbot", "joonbot-com"],
  ["JotUrl Conversion Code Template", "juongithub"],
  ["Journify tracker", "journifyio"],
  ["jQuery loader", "merkle-es"],
  ["jsDelivr", "luratic"],
  ["JSON Tag", "floriangoetting"],
  ["JUS. Cookie Management (CMP)", "JUSPoint"],
  ["Kakao", "luratic"],
  ["Kanaree.io - Official Tracking Template", "Kanaree"],
  ["Kargo Pixel", "KargoGlobal"],
  ["Kelkoogroup Sales Tracking Tag", "KelkooGroup"],
  ["Ketch CMP (Consent Mode)", "ketch-com"],
  ["Kieskeurig.nl", "reshift"],
  ["Klaviyo Hospitality Tracking", "klaviyo"],
  ["Klaviyo Identify", "stape-io"],
  ["Klaviyo Tracking", "FrantisekFr"],
  ["Knotch", "KnotchLabs"],
  ["Kommo Website chat button", "kommo-crm"],
  ["Kompassify", "kompassify"],
  ["KrystalView Analytics", "KrystalView"],
  ["Kukie CMP", "kukie-io"],
  ["Kwai Pixel", "kwai"],
  ["Kwanko Default Tag", "kwanko"],
  ["Kwanko Universal Conversion Tag", "kwanko"],
  ["Ladenzeile Conversion Tag", "ladenzeile"],
  ["Ladenzeile Landing Tag", "ladenzeile"],
  ["Landbot - Main Library", "luratic"],
  ["Lawwwing CMP", "lawwwing"],
  ["Laylo Pixel", "Laylo"],
  ["lead-alliance container", "lead-alliance"],
  ["Leadbehavior", "LeadBehavior"],
  ["LeadBoxer Tag", "leadboxer"],
  ["Leadfeeder", "Leadfeeder"],
  ["Leadinfo", "LeadinfoHQ"],
  ["Leadsourcing Tracking Tag", "lead-sourcing"],
  ["LeadTracker Tag", "leadtrackr"],
  ["Leanplum", "Leanplum"],
  ["Lefty Conversion Pixel", "leftyio"],
  ["legal web Consent Mode Template", "legalwebio"],
  ["LegalBlink CMP", "hirooks-legalblink-it"],
  ["Legitimuz SDK", "legitimuzbr"],
  ["Lentainform Pixel", "lentainform"],
  ["LianaAutomation", "lianahq"],
  ["Ligatus", "luratic"],
  ["LightBeam CMP", "lightbeamai"],
  ["LINEヤフー広告 サイトジェネラルタグ", "yahoojp-marketing"],
  ["LINEヤフー広告 ディスプレイ広告 - コンバージョン測定タグ", "yahoojp-marketing"],
  ["LINEヤフー広告 ディスプレイ広告 - サイトリターゲティングタグ", "yahoojp-marketing"],
  ["LINEヤフー広告（検索広告） - コンバージョン測定タグ", "yahoojp-marketing"],
  ["LINEヤフー広告（検索広告） - サイトリターゲティングタグ", "yahoojp-marketing"],
  ["LINEヤフー広告（検索連動型ショッピング広告） - Conversion測定タグ", "yahoojp-marketing"],
  ["LinkedIn Conversion", "luratic"],
  ["LinkedIn InsightTag 2.0", "linkedin"],
  ["LiquidM Universal Pixel", "liquidm"],
  ["Lisio", "Lisio-solutions"],
  ["LiveChat Tag", "livechat"],
  ["LiveRamp", "LiveRamp"],
  ["LiveSession", "livesession"],
  ["Local Storage Interact", "gtm-templates-anto-hed"],
  ["Localize TMS Integration", "Localize"],
  ["Log To Console", "mbaersch"],
  ["Lucky Orange", "luratic"],
  ["Lunio MPlat", "luniohq"],
  ["Lytics", "lytics"],
  ["Made with Intent Add To Cart", "madewithintent-labs"],
  ["Made with Intent Pageview", "madewithintent-labs"],
  ["Made with Intent Purchase", "madewithintent-labs"],
  ["Made with Intent Tag", "madewithintent-labs"],
  ["Magellan.AI Attribution Pixel", "magellan-ai"],
  ["Mailchimp Site Tracking Pixel", "mailchimp"],
  ["Mailerlite", "luratic"],
  ["Mandatly CMP", "mandatly-inc"],
  ["Mapp Cloud Tracking", "mapp-digital"],
  ["Master of Cookies CMP", "masterofcookies"],
  ["matelso Call Tracking", "matelso"],
  ["Matomo Analytics - Actions", "data-marketing-school"],
  ["Matomo Analytics - Configuration", "data-marketing-school"],
  ["Matomo Analytics - Content Tracking", "data-marketing-school"],
  ["Matomo Analytics - E-commerce Tracking", "data-marketing-school"],
  ["Matomo Analytics (formerly Piwik)", "trackify-info"],
  ["Matomo Custom Dimension", "openmost"],
  ["Matomo Event", "openmost"],
  ["Matomo Event & Goal Tracking", "matomo-org"],
  ["Matomo Goal", "openmost"],
  ["Matomo Site Search", "openmost"],
  ["Matomo Tracking Tag for Matomo Cloud", "matomo-org"],
  ["Matomo Tracking Tag for Matomo Cloud", "okkidev01"],
  ["Mautic Event", "leoschuler"],
  ["Mautic Lead Tracking Event", "HAGARAUJO"],
  ["Mautic Lead Tracking Event", "alled7"],
  ["Mautic Tracking (with User Consent)", "leoschuler"],
  ["Mediabids Conversion", "Mediabids"],
  ["Mediabids Visit", "Mediabids"],
  ["MediaGo Pixel", "Baidu-MediaGo"],
  ["Mediahawk Call Conversion Tracking", "mediahawk-ltd"],
  ["mediasmart Conversion Tracking", "mediasmart"],
  ["Mentioned App", "MentionedHQ"],
  ["Merkle Survey", "Merkle-Analytics-Sweden"],
  ["Merkle Survey - Event Push", "Merkle-Analytics-Sweden"],
  ["Meru Data CCM", "MeruData"],
  ["Meta Pixel", "facebook"],
  ["Metaピクセル・設定タグ", "BruceClayJapan"],
  ["mFilterit Visit Pixel", "santosh-mf"],
  ["mFilterit Visit Tag - Santosh", "santosh-mf"],
  ["MGID Pixel", "mgid"],
  ["MGskyads", "MGskyads"],
  ["mHub Cloud Event", "crossmasters"],
  ["Microsoft Clarity", "luratic"],
  ["Microsoft Clarity - Official", "microsoft"],
  ["Microsoft Clarity Events", "mbaersch"],
  ["Microsoft UET Consent Mode", "mbaersch"],
  ["MiQ Pixel Template", "skchan2"],
  ["Mirakl tag", "mirakl"],
  ["Mixpanel", "mixpanel"],
  ["MNTN Conversion Pixel", "MNTNdigital"],
  ["MNTN Tracking Pixel", "MNTNdigital"],
  ["Modio.cz tracking pixel", "modio-cz"],
  ["Moesif API Analytics", "Moesif"],
  ["Monetate", "luratic"],
  ["Monita DataLayer Monitoring", "rnadigital"],
  ["Monita Global Monitoring", "rnadigital"],
  ["Monita Tag Monitoring", "rnadigital"],
  ["Mopinion Deployment", "mopinion"],
  ["Mouseflow Advance Unofficial Template", "Jude-Nwachukwu"],
  ["MoveoOne", "divstechnologydev"],
  ["mParticle - Event - Commerce Template", "mparticle-solutions"],
  ["mParticle - Event - Custom Template", "mparticle-solutions"],
  ["mParticle - Event - Screen View Template", "mparticle-solutions"],
  ["mParticle - IDSync Template", "mparticle-solutions"],
  ["mParticle - Initialization Template", "mparticle-solutions"],
  ["mParticle by Rokt - Event - Commerce Template", "ROKT"],
  ["mParticle by Rokt - Event - Custom Template", "ROKT"],
  ["mParticle by Rokt - Event - Screen View Template", "ROKT"],
  ["mParticle by Rokt - Events", "ROKT"],
  ["mParticle by Rokt - IDSync Template", "ROKT"],
  ["mParticle by Rokt - Initialization and Log Page View", "ROKT"],
  ["MVT Tester", "chriswalton"],
  ["My ONE Dot", "oneagencycom"],
  ["MyAgilePrivacy CMP", "MyAgilePrivacy"],
  ["Nantu A/B Test", "nantuapp"],
  ["Narrator-sdk", "kiozk-russia"],
  ["NetGo.hu Cookie Consent", "netgohu"],
  ["Netka CMP", "netkasystem"],
  ["NeuBidsPixel", "lutkan"],
  ["Nextdoor Universal Pixel", "Nextdoor"],
  ["Nexus Event", "Alliance-Innovations"],
  ["Nimbata Call Tracking", "Nimbata"],
  ["Ninetailed", "ninetailed-inc"],
  ["No Ads by Adless", "adless-tech"],
  ["Noibu", "Noibu"],
  ["Noor Insights Gravity Form Integration", "NoorProjects"],
  ["Octanist - Offline Conversion Tracking", "Octanist"],
  ["OddBytes Pixel Conversion Tracking", "OddBytesPlatform"],
  ["OFFICIAL Lucky Orange Tracking Code", "luckyorange"],
  ["Official Yandex Metrica", "yandex"],
  ["Ogury Post Click Tracker", "Ogury"],
  ["Okito CMP", "okitocmp"],
  ["OKSpin E-Commerce", "okspin"],
  ["Olo Serve", "ololabs"],
  ["OneTrust CMP", "OneTrustCMP"],
  ["OpenAI Ads Measurement Pixel", "openai"],
  ["OpenAI Ads Pixel by Stape", "stape-io"],
  ["OpentrackerGrowthTag", "Opentracker"],
  ["OpenWidget Tag", "livechat"],
  ["Opinary-OTB-embed", "opinary"],
  ["Opinary-TP-event", "opinary"],
  ["Opinary-TP-init", "opinary"],
  ["Opticks Conversion Tag", "OpticksSecurity"],
  ["Opticks Sensor", "OpticksSecurity"],
  ["Optimise Conversion Tag", "optimisemediagroup"],
  ["Optimise Universal Tag", "optimisemediagroup"],
  ["Orbee Consent Mode for GTM", "OrbeeInc"],
  ["Orbee Script Install", "OrbeeInc"],
  ["Oribi", "MISTAnalytics"],
  ["Osano Consent Manager", "osano"],
  ["Outbrain Enhanced", "luratic"],
  ["Outbrain Pixel", "outbrain-inc"],
  ["Outfindo pageview tag", "outfindo"],
  ["Paboo pixel", "Empi-Tech"],
  ["Page Speed Booster", "patrickschababerle"],
  ["PageSense Tag", "PageSense"],
  ["Pandectes CMP", "pandectes"],
  ["Pardot Tracking - GET Request", "taneli-salonen1"],
  ["Parse.ly", "Parsely"],
  ["Partnerize Custom Tracking Tag", "PZ-it-admin"],
  ["Partnerize Enhanced eCommerce Tag", "PZ-it-admin"],
  ["Partnerize GA4 eCommerce Tag", "PZ-it-admin"],
  ["Partnerize Standard eCommerce Tag", "PZ-it-admin"],
  ["Pathmonk - AI Marketing Suite", "pathmonk"],
  ["Perfection.dev", "perfectiondotdev"],
  ["PerformCB Measurement Tag", "performcb"],
  ["Permate Button Tag", "permate-tech"],
  ["Permate Conversion Tag", "permate-tech"],
  ["Permate SuperTag", "permate-tech"],
  ["Persado Click Tracker", "persado"],
  ["Persado Conversion Tracker", "persado"],
  ["Persado Generic Tracker", "persado"],
  ["Persist Campaign Data", "gtm-templates-simo-ahava"],
  ["Personyze Tracking", "personyze"],
  ["Phoenix Ads Base Code", "cloudview-tech"],
  ["Phoenix Ads Event Code", "cloudview-tech"],
  ["Piano Analytics - Tagging", "at-internet"],
  ["Piano Analytics S2S - Transporteur", "OptimizeMatter"],
  ["Picked", "picked-app"],
  ["PieEye Consent Mode", "pieeyeinc"],
  ["Pingdom Visitor Insights (RUM)", "alexminza"],
  ["Pinterest Pixel Tag", "pinterest"],
  ["Pipedrive Leadbooster Chatbot", "luratic"],
  ["Piwik PRO Analytics", "PiwikPRO"],
  ["Piwik PRO Anonymous Mode", "anthonybartczak"],
  ["Pixel Livelo Partner", "Metricaz"],
  ["Pixibo Find Your Fit", "pixibo"],
  ["Plausible Analytics", "plausible"],
  ["plista Conversion Plus event", "WPP-Public"],
  ["plista Conversion Plus integration", "WPP-Public"],
  ["PM Client-side Integration - All pages", "Profitmetrics-io"],
  ["PM Client-side Integration - Purchase", "Profitmetrics-io"],
  ["PM Pixel Tag - QA", "PmHubDev"],
  ["PM Serverside Hybrid Universal Integration Script", "Profitmetrics-io"],
  ["Podscribe", "podible"],
  ["Podsights Script", "maxisdigital"],
  ["Politweets by Whole Whale", "WholeWhale"],
  ["Poltio", "Poltio"],
  ["Popbrain Ads Pixel", "Popbrainads"],
  ["popIn web popup", "popIn-Discovery"],
  ["Poptin Popups and Forms", "poptins"],
  ["Post A Job", "postajob"],
  ["Postajob Conversion", "postajob"],
  ["Postajob Tag", "postajob"],
  ["Pressidium Cookie Consent", "pressidium"],
  ["Privacybee consent management template", "privacybee-ag"],
  ["PrivacyPillar Consent Manager - CMP", "PrivacyPillar"],
  ["Privy CMP", "idfy"],
  ["Prodiax - UX Analytics SDK", "prodiax"],
  ["Profity Conversion Tracking", "adfocus-tech"],
  ["Progress Sitefinity Insight", "Sitefinity"],
  ["Promptwatch - Visitor Analytics", "promptwatch-com"],
  ["Propel Media Pixel Conversion Tracking", "PropelMediaPlatform"],
  ["ProveSource", "provesource"],
  ["Ptbwa Insight Pixel", "PerformanceByTBWA"],
  ["Pubtech CMP", "pubtech-ai"],
  ["Pulse - Pixel Monitor", "articdigital"],
  ["Purchase Validator", "mbaersch"],
  ["Pushnews", "luratic"],
  ["PushNinja - 500apps", "agilecrm"],
  ["PushPanda.io Tag", "PushPandaHQ"],
  ["Qooqie Call Tracking", "Tam-One"],
  ["Qualaroo", "gtm-templates-simo-ahava"],
  ["Qualaroo", "qualaroo"],
  ["Quality Hive", "qualityhiveapp"],
  ["Quantum Metric JS Tag", "quantummetric"],
  ["questFON Call-Tracking by Telequest", "TelequestInternetSolutionsGmbH"],
  ["Queue-Fair Virtual Waiting Room Adapter", "Queue-Fair"],
  ["Quikly GTM Template", "quikly"],
  ["Quin AI", "quinai"],
  ["Qwarry Conversion", "Qwarry"],
  ["Qwarry ID persistence", "Qwarry"],
  ["Rakuten Advertising Performance Tag - Conversion", "Rakuten-Advertising-Developers"],
  ["Rakuten Advertising Performance Tag - Global", "Rakuten-Advertising-Developers"],
  ["Raptor Event Tracking", "RaptorServices"],
  ["Raptor Main", "RaptorServices"],
  ["Raventic Recommendations Carousel", "Raventic"],
  ["Raventic Semantic Search Integration", "Raventic"],
  ["Raventic Semantic Search Modal Widget", "Raventic"],
  ["RCMX Tag", "rcm1x"],
  ["ReaLift WebSDK", "Realift"],
  ["Recite Me Accessibility Toolbar", "ReciteMe"],
  ["Recite Me Toolbar", "recite-me-richard"],
  ["Recombee Shoptet interactions", "recombee"],
  ["Record Sale Conversion (Shoptet)", "prstynek-com"],
  ["Recreativ Conversion", "recreativ"],
  ["Reddit Pixel", "reddit"],
  ["Redfast Active User Personalization", "redfast"],
  ["Redirect to HTTPS", "sushiljainam"],
  ["Reelevant Website Tracking Tag", "reelevant-tech"],
  ["Refiner", "refiner-io"],
  ["Reflektion", "Reflektion"],
  ["ReklamStore Affiliate Conversion Pixel", "ReklamStoreIT"],
  ["Retail Rocket", "RetailRocket"],
  ["RetailorID - Retailor Media", "RetailorMedia"],
  ["RetJet - customer return/warranty form", "RetJet"],
  ["Rezfusion Hub Transaction Builder", "PropertyBrands"],
  ["RightcliQ", "nosagent"],
  ["Ringostat V4", "Lunaxod"],
  ["Ripe SDK", "getripe"],
  ["RixDesk Pixel", "RixEngine"],
  ["Roadtrip Explorer", "roadtriptechnologies1"],
  ["Rokt Tag Integration", "ROKT"],
  ["Roku Pixel", "roku-oss"],
  ["RTB House Hosted Tag", "RTBHOUSE"],
  ["RudderStack Template", "rudderlabs"],
  ["SafeOpt - Conversion Tag", "addshoppers"],
  ["SafeOpt - Global Site Tag", "addshoppers"],
  ["Sales Tracking Ladenzeile", "ladenzeile"],
  ["SalesAutopilot - Save UTM Tags to LocalStorage", "salesautopilot"],
  ["Salesfire GTM Template", "salesfire"],
  ["Salesforce Audience Studio", "luratic"],
  ["Salesforce Data Cloud Event Ingestion", "salesforce-misc"],
  ["Salesmanago", "restaurantclub"],
  ["SalesViewer®", "SalesViewer"],
  ["SalesWings", "SalesWings"],
  ["SalesWings Custom Event", "SalesWings"],
  ["Samelogic", "samelogic"],
  ["Saola Recorder", "omrilotan"],
  ["SatisMeter NPS surveys", "satismeter"],
  ["Screeb", "ScreebApp"],
  ["Script injector", "shulhat"],
  ["Sealmetrics Tracking", "sealmetrics"],
  ["Secure Privacy CMP", "secureprivacy"],
  ["Securiti, Inc. CMP", "securitiai"],
  ["Seeding Alliance Pixel", "SeedingAllianceTech"],
  ["Seeka install", "seeka-labs"],
  ["Seers CMP & Cookie Banner", "NickSpencer511"],
  ["Segment", "slide-rule-tech"],
  ["Segmint Marketing Platform", "segmintinc"],
  ["Selltoro.com Tracking Pixel", "srovname-cz"],
  ["Send Pixel", "demirj"],
  ["Sensefuel", "Sensefuel"],
  ["Sentifyd Avatar", "Sentifyd"],
  ["Sentry", "omrilotan"],
  ["SEO Sessions (for GA4)", "IKAUE-Development"],
  ["Serenity Chat", "Serenity-AI-Hub"],
  ["Serverside events bridge", "CommandersAct"],
  ["Session Rewind", "SessionRewind"],
  ["SevenRooms install", "seeka-labs"],
  ["Seznam SEM", "pavelsabatka"],
  ["Sfbx - AppConsent CMP - Default Consent Mode", "sfbx-io"],
  ["Sfbx AppConsent CMP Setup", "sfbx-io"],
  ["ShinyStat Analytics - Events tracking", "shinystat"],
  ["ShinyStat Analytics - Tracking Code", "shinystat"],
  ["Shoparize Partner Tracking", "shoparize"],
  ["Shoparize Website Tracking API", "Andiministrator"],
  ["Shopify Customer Privacy API", "stape-io"],
  ["ShoppingGives", "NicheInteractiveMedia"],
  ["Signals Gateway Pixel by Stape", "stape-io"],
  ["SignalsGateway Pixel - Alpha - v0", "facebookincubator"],
  ["Simple Analytics", "simpleanalytics"],
  ["Simple Cookie Creator", "NormanHoehne"],
  ["Singular Web Tracking", "singular-labs"],
  ["Siteimprove Unofficial", "Jude-Nwachukwu"],
  ["Sizmek Conversion Activity", "Quadratic-Insights"],
  ["Sklik", "pavelsabatka"],
  ["Sklik & Zbozi.cz", "marketingmakers"],
  ["SkyGlue - Event Tracking for Google Analytics", "yhh4551"],
  ["Slack Webhook", "measureschool"],
  ["Sleeknote", "Sleeknote"],
  ["Sleekplan Tag (unofficial)", "muradsofi"],
  ["Slymetrix Analytics", "slymetrix"],
  ["Smartarget Whatsapp Chat", "erezson"],
  ["Smartlook", "smartlook"],
  ["Smartlook Advanced Unofficial", "Jude-Nwachukwu"],
  ["Smartsearch Tag Template", "bigshoppernl"],
  ["SmartTag", "etagdigital-cro"],
  ["Smilee Chat Tag", "smileeio"],
  ["Snap Pixel", "Snapchat"],
  ["Snapchat", "luratic"],
  ["Snoobi Analytics", "snoobitechnology"],
  ["Snowplow Analytics", "snowplow-archive"],
  ["Snowplow Ecommerce", "snowplow"],
  ["Snowplow v3", "snowplow"],
  ["Snowplow v4", "snowplow"],
  ["SocialCAPI.com", "socialcapi-com"],
  ["Socital", "Socital"],
  ["Soicos Conversion", "soicos-fj"],
  ["Soreto", "soreto"],
  ["SourceKnowledge Conversion Tag", "sokno"],
  ["Sourcepoint CMP - Consent Mode v2", "SourcePointUSA"],
  ["Sovendus Checkout Products Postback", "Sovendus-GmbH"],
  ["Sovendus Integration for Voucher Network and Checkout Benefits", "Sovendus-GmbH"],
  ["Sovendus Optimize", "Sovendus-GmbH"],
  ["Spectacle", "Spectacle-HQ"],
  ["Spindl Tag Template", "spindl-xyz"],
  ["Sportradar Tag Manager", "ads-marketing-cloud"],
  ["Sprig Tag", "UserLeap"],
  ["Springtime Consent Management Template", "audioeye"],
  ["Squadata eMail SMS Retargeting", "lmugnier"],
  ["Squeezely CDP", "analytics-engineers"],
  ["Srovnáme.cz Tracking Pixel", "srovname-cz"],
  ["Start.io Pixel", "startappdev"],
  ["streamboost Conversion-Tag", "streamboost-GmbH"],
  ["STRiGHT CMP", "stright-tech"],
  ["Studyportals Pixel", "luratic"],
  ["Stylight Sales Confirmation", "stylight"],
  ["Stylight Sales Identifier", "stylight"],
  ["SUMR - Visitas", "serviciosinco"],
  ["Supreme Tracking Event Core", "theofelo"],
  ["Switch Boost", "switchgrowth"],
  ["Syndic Marketing Nexus Pixel", "syndicinc"],
  ["Sypher Cookie Consent CMP", "syphereu"],
  ["Syrenis CMP", "trustcassie"],
  ["Taboola Pixel", "taboola"],
  ["Tag Concierge Consent Mode Banner", "tagconcierge"],
  ["Tag Insight Pixel", "tagexpert"],
  ["Tag Monitor for GA", "42DIGITAL"],
  ["TagFly GDPR CMP", "tagfly"],
  ["Taggernauta Tag", "nicozanellato"],
  ["Tagglo Tag Monitor", "tagglo"],
  ["TAGGRS tracking tag - client side", "TAGGRS"],
  ["Taglayer Personalization Library", "taglayer"],
  ["TagServer Data Tag", "TagServer"],
  ["Tailor AI", "tailor-hq"],
  ["Talkie by Audience Talking", "AudienceTalkingGroup"],
  ["Tangoo Master Tag", "TangooMediaSRL"],
  ["Tapfiliate Event Tag", "newnorthdigital"],
  ["Tapper - Event Dispatcher", "tapperai"],
  ["Tapper - Identifier Setter", "tapperai"],
  ["Tapper - Monitoring Script", "tapperai"],
  ["Targito Tracking", "targito"],
  ["Teads Advertiser Pixel", "teads"],
  ["Teads Publisher Cookieless Tag", "teads"],
  ["Tealium Collect Tag", "Tealium"],
  ["Tealium Cookie Match", "Tealium"],
  ["Tealium Data Enrichment", "Tealium"],
  ["Teko Facebook Pixel Add to cart", "teko-vn"],
  ["Teko Facebook Pixel Checkout", "teko-vn"],
  ["Teko Facebook Pixel Purchase event", "teko-vn"],
  ["Telliclick Tag", "basetime"],
  ["Termly Consent Management Platform", "termly"],
  ["TermsFeed Cookie Consent (4.1)", "termsfeed"],
  ["Ternair Marketing Cloud Clicks Tracking", "Ternair-Software"],
  ["The Hotels Network (THN)", "mindbreaker"],
  ["The Trade Desk Conversion Events JS SDK", "thetradedesk"],
  ["Thinking Engine", "wo123kr"],
  ["TikTok", "luratic"],
  ["TikTok Pixel", "tiktok"],
  ["TikTok Pixel by Stape", "stape-io"],
  ["Time Since Last Session for GA4", "shulhat"],
  ["TimeOne - Global Tag", "TimeOne-Group"],
  ["TimeOne - SDK", "TimeOne-Group"],
  ["TimeOne - SDK - Conversion", "TimeOne-Group"],
  ["TimeOne - SDK - Intégration CMP", "TimeOne-Group"],
  ["TimeOne - SDK - Tag de conversion", "TimeOne-Group"],
  ["TimeOne - Tag de conversion", "TimeOne-Group"],
  ["TNCiD - The Newco", "TheNewco"],
  ["Tomi AI Lead Submit", "tomiai"],
  ["Tomi.AI Pixel", "tomiai"],
  ["Track Core Web Vitals", "IKAUE-Development"],
  ["Trackify Free Consent CMP", "trackify-info"],
  ["Tracking-Expert CMP", "Experteam-ET"],
  ["TrackJS Agent", "alexminza"],
  ["Tracklution", "tracklution"],
  ["Tracknow", "TracknowLTD"],
  ["Tradedoubler", "tradedoubler"],
  ["TradeTracker.com", "tradetracker-com"],
  ["TrafficGuard Conversion Tracker Tag", "trafficguard-hq"],
  ["TrafficGuard Site Tracker Tag", "trafficguard-hq"],
  ["TrafficMile Pixel Tracking", "ivebe"],
  ["Transaction ID Logger", "gtm-templates-simo-ahava"],
  ["trbo", "NormanHoehne"],
  ["trbo Plugin-Code", "trbocom"],
  ["Trengo Widget", "newnorthdigital"],
  ["TriAD CTV Pixel", "triad-ctv"],
  ["TribeOS Tracking Pixel", "TribeOS"],
  ["Triggerbee Event Logging 2.0", "Triggerbee-AB"],
  ["Triggerbee Tracking", "Triggerbee-AB"],
  ["Trinity Audio", "TrinityAudioSDK"],
  ["Triptease", "mindbreaker"],
  ["Trovaprezzi Trusted Program", "7pixel"],
  ["TRUENDO Cookie Consent Management", "truendo-tech"],
  ["TrueVault Polaris CMP", "truevault"],
  ["TrustArc CMP (Consent Mode)", "trustarc"],
  ["TrustArc Google Consent Mode v2 - BETA", "trustarc"],
  ["Trusted Shops Tag", "newnorthdigital"],
  ["TrustedSite Certification", "TrustedSite"],
  ["TrustProfile", "trustprofileio"],
  ["Truyo CMP", "Truyo-dba-IntraEdge"],
  ["TUNE Tag", "tuneinc"],
  ["tuto loader", "tutoit-io"],
  ["TV Tag Manager", "tvty-official"],
  ["tvScientific Universal Site Pixel", "tvScientific"],
  ["TVTY - Measure - TV To Web - Basic", "tvty-official"],
  ["Tweex", "tweex-technologies"],
  ["Twenga Pixel", "Twenga"],
  ["Twinalyze Web Analytics SDK", "twinalyze"],
  ["TWIPLA", "twipla"],
  ["Twitter Base Pixel", "twitter"],
  ["Twitter Event Pixel", "twitter"],
  ["TYPO3 we_cookie_consent CMP", "websedit"],
  ["Tyviso", "tyviso"],
  ["UA to GA4 Event Converter", "pluszero-global"],
  ["UCreate RS Affiliate Conversion Pixel", "ReklamStoreIT"],
  ["UIM Profiling Container", "united-internet-media"],
  ["UniConsent CMP", "transfon"],
  ["Universal Ads Pixel", "Universal-Ads"],
  ["Universal Consent Adapter", "piotrlitwa"],
  ["Unless Monitor", "unlessdotcom"],
  ["Uptok Priority", "uptok"],
  ["URL to Cookie or Local Storage", "jjbernalgarcia"],
  ["User Data Collector From Page", "stape-io"],
  ["User Data Listener", "analyticskgmedia"],
  ["User Data Restorer", "analyticskgmedia"],
  ["User Distributor", "gtm-templates-simo-ahava"],
  ["User Property and Data Manager", "Jude-Nwachukwu"],
  ["Usercentrics CMP", "Usercentrics"],
  ["Userpilot", "gtm-templates-simo-ahava"],
  ["UserReport", "audienceproject"],
  ["Utiq Technology", "UtiqTech"],
  ["UTM Simple v1", "handldigital"],
  ["UTM_Cookie_Store", "spyder-com-tw"],
  ["UTM_Cookie_Store", "spydertracking"],
  ["UTM_Whatsapp - by @jaimeflneto", "jaimeneto85"],
  ["Uxify", "uxify-ltd"],
  ["Uzerly Global Tag", "uzerly"],
  ["Value Hasher", "jamescottrill"],
  ["Vaven Tag", "vaven-platform"],
  ["Venofy", "moatasem-areeny"],
  ["Verfacto Custom Event", "Verfacto"],
  ["Verfacto Tracker", "Verfacto"],
  ["Verifalia Email Verification Widget", "verifalia"],
  ["Vibe Pixel", "vibe-ad"],
  ["Videsk Widget", "videsk"],
  ["Violet Pixel", "Exactius"],
  ["Visable Website Leads", "marbinkaraus"],
  ["Visitor Intelligence", "DnB-Andrew"],
  ["VisitorAPI", "visitorapi"],
  ["VK Pixel", "d9i2r2t1"],
  ["VK Pixel&Retarget DEMO", "novergeme"],
  ["VO Cookie Consent Manager", "vOfficer"],
  ["Void Analytics integration", "VoidAnalytics"],
  ["Volumental Conversion", "Volumental"],
  ["Volumental Sizing", "Volumental"],
  ["Voyantis", "Voyantis"],
  ["Vtools Geo Location", "vtools-solutions"],
  ["VWO (Wingify) Event Streamer", "wingify"],
  ["walker.js Event", "elbwalker"],
  ["Waulter consent management (cookie and other consents management)", "Consentizer"],
  ["Web tag for GoogleTagManager", "facebookincubator"],
  ["webePartners", "theshoperman"],
  ["Webmetic", "yanniksuess"],
  ["WebMinds Cookie Consent Banner", "webminds-inc"],
  ["Weborama", "luratic"],
  ["Weborama Conversion", "Weborama"],
  ["WebToffee CMP", "WebToffee"],
  ["webtru CMP(同意管理ツール)", "datasign-inc"],
  ["Webview to App conversion", "IKAUE-Development"],
  ["WebwinkelKeur", "webwinkelkeur"],
  ["Webyn – Better Shopping Experience", "webyn-ai"],
  ["Whatsapp Chat Icon", "leoschuler"],
  ["Wide Angle Analytics", "wideangleanalytics"],
  ["WiderPlanet Tag Script", "Widerplanet-gtm"],
  ["Winfluencer Tracking Template", "randicortexlabs"],
  ["Wondaris Collection Tag", "Wondaris"],
  ["WonderPush - Integrate Web Push Notifications", "wonderpush"],
  ["WonderPush - Manage tags and properties", "wonderpush"],
  ["WonderPush - Track event", "wonderpush"],
  ["WOVN.io Javascript Widget", "WOVNio"],
  ["WP Nordic - Cookie Care Consent Mode v2", "WPNordic"],
  ["WPConsent - WordPress Privacy Compliance Made Easy", "awesomemotive"],
  ["WPLP Compliance Platform", "wpeka"],
  ["Wygodne Zwroty", "AlleKurier"],
  ["Xandr config", "Knapstad"],
  ["XDID", "xdid-net"],
  ["XDID Facebook Pixel", "xdid-net"],
  ["XDID Injector - Append", "xdid-net"],
  ["XDID Injector - Replace", "xdid-net"],
  ["XDID Webhook", "xdid-net"],
  ["XDID Webhook Email", "xdid-net"],
  ["XDID Webhook Recommendations", "xdid-net"],
  ["XDID Webhook Stats", "xdid-net"],
  ["Xiaomi Ads Pixel", "iibxiaomi2025"],
  ["XO Activities Tracking", "Attraqt"],
  ["XO Multi-Activity Tracking", "Attraqt"],
  ["Yahoo Dot Pixel", "yahoo"],
  ["Yandex Metrica", "analytics-debugger"],
  ["Yandex Metrika Varioqub AB-tests", "Firnis"],
  ["Yandex.Metrica 🇪🇸", "antoniolite"],
  ["Yext Analytics Browser SDK", "yext"],
  ["Yext Conversion Tracking - Conversion Tag", "yext"],
  ["Yext Conversion Tracking - Listings Tracking Tag", "yext"],
  ["YouTube iframe API loader", "gtm-templates-simo-ahava"],
  ["YWT Call Tracking", "yeswetrack"],
  ["Zbozi.cz Conversion", "House-of-Rezac"],
  ["Zemanta Pixel", "Zemanta"],
  ["Zeotap Collect Tag Template", "zeotap"],
  ["Zeotap ID+ Tag", "zeotap"],
  ["Zigpoll", "newnorthdigital"],
  ["Zoominfo Pixel", "holini"],
  ["Zurvey - popup survey", "neticlecom"],
  ["タナカサン-マイクロサーベイ", "iDEAKITT"],
  ["パッとブライダルGAクロスドメイン用タグ", "paplea"],
  ["計測タグ イベントスニペット（LINEヤフー）", "yahoojp-marketing"],
  ["計測タグ グローバルスニペット（LINEヤフー）", "yahoojp-marketing"],
];

export const GALLERY_SNAPSHOT_DATE = '2026-08-27';
